HOOK(PKG_PLUGIN_HOOK_PRE_INSTALL, pre_install, "PRE:INSTALL")
HOOK(PKG_PLUGIN_HOOK_POST_INSTALL, post_install, "POST:INSTALL")
HOOK(PKG_PLUGIN_HOOK_PRE_DEINSTALL, pre_deinstall, "PRE:DEINSTALL")
HOOK(PKG_PLUGIN_HOOK_POST_DEINSTALL, post_deinstall, "POST:DEINSTALL")
// PKG_PLUGIN_HOOK_PRE_FETCH
// PKG_PLUGIN_HOOK_POST_FETCH
// PKG_PLUGIN_HOOK_EVENT
HOOK(PKG_PLUGIN_HOOK_PRE_UPGRADE, pre_upgrade, "PRE:UPGRADE")
HOOK(PKG_PLUGIN_HOOK_POST_UPGRADE, post_upgrade, "POST:UPGRADE")
HOOK(PKG_PLUGIN_HOOK_PRE_AUTOREMOVE, pre_autoremove, "PRE:AUTOREMOVE")
HOOK(PKG_PLUGIN_HOOK_POST_AUTOREMOVE, post_autoremove, "POST:AUTOREMOVE")
// PKG_PLUGIN_HOOK_PKGDB_CLOSE_RW
